<?php

namespace Database\Seeders;

use App\Models\Anfrage;
use App\Models\Markt;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class AnfrageSeeder extends Seeder
{
    public function run(): void
    {
        // First create a market if it doesn't exist
        $markt = Markt::firstOrCreate(['id' => 1], [
            'name' => 'Test Markt',
            'datum' => now(),
            'ort' => 'München',
        ]);

        // Generate random timestamps within the last 2 days
        $now = Carbon::now();
        $twoDaysAgo = $now->copy()->subDays(2);

        // Create 15 records
        $records = [
            [
                'markt_id' => 1,
                'firma' => 'Sistecs Media Agentur',
                'anrede' => 'Herr',
                'vorname' => 'Michael',
                'nachname' => 'Benker',
                'strasse' => 'Josef-Herz-Str. 25',
                'hausnummer' => null,
                'plz' => '85435',
                'ort' => 'Erding',
                'land' => 'Deutschland',
                'telefon' => '491708666718',
                'email' => 'mb@sistecs.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kleidung'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'irgendwas',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Sistecs Media',
                'anrede' => 'Herr',
                'vorname' => 'M.',
                'nachname' => 'Benker',
                'strasse' => 'Josef-Herz-Str. 25',
                'hausnummer' => null,
                'plz' => '85435',
                'ort' => 'Erding',
                'land' => 'Deutschland',
                'telefon' => '491708666718',
                'email' => 'michael.benker@sistecs.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kleidung'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Variante 2',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Sistecs',
                'anrede' => 'Herr',
                'vorname' => 'Michael',
                'nachname' => 'B.',
                'strasse' => 'Josef-Herz-Str. 25',
                'hausnummer' => null,
                'plz' => '85435',
                'ort' => 'Erding',
                'land' => 'Deutschland',
                'telefon' => '491708666718',
                'email' => 'mb@sistecs.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kleidung'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Variante 3',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Müller & Schmidt GmbH',
                'anrede' => 'Frau',
                'vorname' => 'Anna',
                'nachname' => 'Müller',
                'strasse' => 'Hauptstraße',
                'hausnummer' => '42',
                'plz' => '80331',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345678',
                'email' => 'anna.mueller@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['schmuck', 'accessoires'],
                'herkunft' => [
                    'eigenfertigung' => 80,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 20
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Erfahrene Ausstellerin',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Kreativwerkstatt',
                'anrede' => 'Herr',
                'vorname' => 'Thomas',
                'nachname' => 'Schmidt',
                'strasse' => 'Kunstweg',
                'hausnummer' => '15',
                'plz' => '81675',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498987654321',
                'email' => 'thomas.schmidt@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kunst', 'handwerk'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Erstmalige Teilnahme',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Bio-Lebensmittel',
                'anrede' => 'Frau',
                'vorname' => 'Maria',
                'nachname' => 'Weber',
                'strasse' => 'Bio-Straße',
                'hausnummer' => '7',
                'plz' => '81369',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345679',
                'email' => 'maria.weber@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['lebensmittel', 'getraenke'],
                'herkunft' => [
                    'eigenfertigung' => 90,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 10
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Bio-zertifiziert',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Antiquitäten-Haus',
                'anrede' => 'Herr',
                'vorname' => 'Peter',
                'nachname' => 'Fischer',
                'strasse' => 'Antik-Gasse',
                'hausnummer' => '3',
                'plz' => '80333',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345680',
                'email' => 'peter.fischer@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['antiquitäten'],
                'herkunft' => [
                    'eigenfertigung' => 0,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 100
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Spezialisiert auf Möbel',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Mode-Atelier',
                'anrede' => 'Frau',
                'vorname' => 'Lisa',
                'nachname' => 'Wagner',
                'strasse' => 'Mode-Straße',
                'hausnummer' => '12',
                'plz' => '80335',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345681',
                'email' => 'lisa.wagner@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kleidung', 'accessoires'],
                'herkunft' => [
                    'eigenfertigung' => 70,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 30
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Nachhaltige Mode',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Kunst-Galerie',
                'anrede' => 'Herr',
                'vorname' => 'Max',
                'nachname' => 'Becker',
                'strasse' => 'Kunst-Allee',
                'hausnummer' => '8',
                'plz' => '80336',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345682',
                'email' => 'max.becker@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['kunst', 'dekoration'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Moderne Kunst',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Schmuck-Design',
                'anrede' => 'Frau',
                'vorname' => 'Sophie',
                'nachname' => 'Hoffmann',
                'strasse' => 'Schmuck-Weg',
                'hausnummer' => '5',
                'plz' => '80337',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345683',
                'email' => 'sophie.hoffmann@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['schmuck'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Handgefertigter Schmuck',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Deko-Studio',
                'anrede' => 'Herr',
                'vorname' => 'Andreas',
                'nachname' => 'Koch',
                'strasse' => 'Deko-Straße',
                'hausnummer' => '9',
                'plz' => '80338',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345684',
                'email' => 'andreas.koch@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['dekoration', 'handwerk'],
                'herkunft' => [
                    'eigenfertigung' => 85,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 15
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Individuelle Dekoration',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Getränke-Spezialitäten',
                'anrede' => 'Frau',
                'vorname' => 'Julia',
                'nachname' => 'Schäfer',
                'strasse' => 'Getränke-Weg',
                'hausnummer' => '4',
                'plz' => '80339',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345685',
                'email' => 'julia.schaefer@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['getraenke'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Regionale Spezialitäten',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Handwerk-Kunst',
                'anrede' => 'Herr',
                'vorname' => 'Martin',
                'nachname' => 'Wolf',
                'strasse' => 'Handwerk-Straße',
                'hausnummer' => '11',
                'plz' => '80340',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345686',
                'email' => 'martin.wolf@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['handwerk', 'kunst'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => true,
                'importiert' => false,
                'bemerkung' => 'Traditionelles Handwerk',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
            [
                'markt_id' => 1,
                'firma' => 'Sonstiges-Kreativ',
                'anrede' => 'Frau',
                'vorname' => 'Sarah',
                'nachname' => 'Meyer',
                'strasse' => 'Kreativ-Weg',
                'hausnummer' => '6',
                'plz' => '80341',
                'ort' => 'München',
                'land' => 'Deutschland',
                'telefon' => '498912345687',
                'email' => 'sarah.meyer@example.de',
                'stand' => ['tiefe' => 3, 'laenge' => 4, 'flaeche' => 12],
                'warenangebot' => ['sonstiges'],
                'herkunft' => [
                    'eigenfertigung' => 100,
                    'industrieware_entwicklungslaender' => 0,
                    'industrieware_nicht_entwicklungslaender' => 0
                ],
                'bereits_ausgestellt' => false,
                'importiert' => false,
                'bemerkung' => 'Kreative Unikate',
                'created_at' => $twoDaysAgo->copy()->addHours(rand(0, 48)),
            ],
        ];

        foreach ($records as $record) {
            Anfrage::create($record);
        }
    }
}
